### Binary classification

Here we will attempt to do a simple binary classification algorithm for the Udacity data.
So first, we load the data

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("C:\\Users\\gonzalezh\\Documents\\Git stuff\\Logistic\\data\\data.csv")

In [18]:
y = df['y']

In [42]:
X = np.concatenate((df['x1'],df['x2']),axis=0).reshape(2,100).T

Now we define the step and prediction functions. 

In [642]:
def stepFunction(t):
    res = 0
    if t >= 0:
        res = 1
    return res


In [643]:
def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

We now implement the preceptron algorithm from the video.

In [186]:
# TODO: Fill in the code below to implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    for k in range(len(y)):
        y_hat = prediction(X[k],W,b)
        W[0] = W[0] + np.sign(y[k] - y_hat) * learn_rate * X[k,0]
        W[1] = W[1] + np.sign(y[k] - y_hat) * learn_rate * X[k,1]
        b = b + np.sign(y[k] - y_hat) * learn_rate
    return W, b

def perceptronStep(X, y, W, b, learn_rate = 0.01):
    for i in range(len(X)):
        y_hat = prediction(X[i],W,b)
        if y[i]-y_hat == 1:
            W[0] += X[i][0]*learn_rate
            W[1] += X[i][1]*learn_rate
            b += learn_rate
        elif y[i]-y_hat == -1:
            W[0] -= X[i][0]*learn_rate
            W[1] -= X[i][1]*learn_rate
            b -= learn_rate
    return W, b




We now generate some random

In [307]:
W = np.array(np.random.rand(2,1))
W

array([[0.3978551 ],
       [0.59891457]])

In [184]:
int(np.matmul(X[0],W)[0])

0

In [190]:
wtf = [prediction(X[k],W,b) for k in range(len(y))]

In [192]:
y[k] - prediction(X[k,],W,b)

-1

In [640]:
W = np.array([[0],[0]])
b = 0

In [641]:

for k in range(1000):
    W,b = perceptronStep(X,y,W,b,learn_rate = 0.9)
    
print(W)
print(b)

[[0]
 [0]]
89999.99999991657


In [645]:
np.exp(0)


1.0

In [646]:
L = [1,2,3]

In [647]:
res = [np.exp(x) for x in L]

In [648]:
res

[2.718281828459045, 7.38905609893065, 20.085536923187668]

In [649]:
sum(res)

30.19287485057736

In [655]:
p = res/sum(res)

In [669]:
print(p)
y = [1,1,0]
y * np.log(p) 
1-y
np.log(1 - p)

[0.09003057 0.24472847 0.66524096]


TypeError: unsupported operand type(s) for -: 'int' and 'list'

In [693]:
def ce(y,p):
    return -sum([a * np.log(b) + (1-a) * np.log(1 - b) for a,b in np.vstack((y,p)).T])

In [692]:
-sum([a * np.log(b) + (1-a) * np.log(1 - b) for a,b in np.vstack((y,p)).T])

[-2.40760596444438, -1.4076059644443801, -1.0943442769261575]

In [691]:
np.vstack((y,p)).T

array([[1.        , 0.09003057],
       [1.        , 0.24472847],
       [0.        , 0.66524096]])

In [694]:
ce([1,1,0],p)

4.909556205814917

In [698]:
x = np.array([[0.4,0.6,1]])
x

array([[0.4, 0.6, 1. ]])

In [713]:
w = np.array([[2,3,5],[6,5,4],[-2,-2.2,-3]])
w
aux = np.matmul(x,w)[0]

In [714]:
[1/(1+np.exp(-v)) for v in aux]




[0.9168273035060777, 0.8807970779778823, 0.8021838885585818]